# Generated by Django 3.0.2 on 2020-01-18 08:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
