# Generated by Django 3.0.2 on 2020-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200118_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(default='pending', editable=False, max_length=50),
        ),
    ]
